version: '3.7'

services:
  backend:
    build: /api
    ports:
      - "8080:8080"
    depends_on:
      - database
    restart: on-failure
    networks:
      - app-network

  database:
    build : /db
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_URL=${POSTGRES_URL}
    volumes:
      - my-vol:/var/lib/postgresql/data
    networks:
      - app-network

  httpd:
    build: /http
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: on-failure
    networks:
      - app-network

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8081:8080"
    networks:
      - app-network
    depends_on:
      - database

networks:
  app-network:
volumes:
  my-vol: